/// supabase_ui — a token-driven, performance-first Flutter design system.
///
/// Layering: tokens → theme → primitives → components. Access the active theme
/// via `context.sb` / `context.sbColors`.
library;

// Tokens.
export 'src/tokens/sb_colors.dart';
export 'src/tokens/sb_spacing.dart';
export 'src/tokens/sb_radius.dart';
export 'src/tokens/sb_typography.dart';
export 'src/tokens/sb_elevation.dart';
export 'src/tokens/sb_motion.dart';

// Theme.
export 'src/theme/sb_theme.dart';
export 'src/theme/sb_theme_extensions.dart';
export 'src/theme/sb_light_theme.dart';
export 'src/theme/sb_dark_theme.dart';
export 'src/theme/sb_app_theme.dart';
export 'src/theme/sb_annonated_region.dart';

// Utils.
export 'src/utils/context_extensions.dart';

// Primitives.
export 'src/primitives/sb_text.dart';
export 'src/primitives/sb_box.dart';
export 'src/primitives/sb_surface.dart';
export 'src/primitives/sb_interaction.dart';

// Components.
export 'src/components/button/sb_button.dart';
export 'src/components/input/sb_text_field.dart';
export 'src/components/input/sb_textarea.dart';
export 'src/components/input/sb_select.dart';
export 'src/components/card/sb_card.dart';
export 'src/components/modal/sb_modal.dart';
export 'src/components/dropdown/sb_dropdown.dart';
export 'src/components/checkbox/sb_checkbox.dart';
export 'src/components/checkbox/sb_tristate_checkbox.dart';
export 'src/components/radio/sb_radio.dart';
export 'src/components/radio/sb_radio_group_stacked.dart';
export 'src/components/switch/sb_switch.dart';
export 'src/components/tooltip/sb_tooltip.dart';
export 'src/components/badge/sb_badge.dart';
export 'src/components/avatar/sb_avatar.dart';
export 'src/components/divider/sb_divider.dart';
export 'src/components/tabs/sb_tabs.dart';
export 'src/components/table/sb_table.dart';
export 'src/components/toast/sb_toast.dart';
export 'src/components/progress/sb_progress.dart';
export 'src/components/skeleton/sb_skeleton.dart';
export 'src/components/alert/sb_alert.dart';
export 'src/components/accordion/sb_accordion.dart';
export 'src/components/sheet/sb_sheet.dart';
export 'src/components/slider/sb_slider.dart';
export 'src/components/segmented/sb_segmented_control.dart';
export 'src/components/navigation/sb_bottom_nav.dart';
export 'src/components/navigation/sb_app_bar.dart';
export 'src/components/list/sb_list_tile.dart';
export 'src/components/chip/sb_chip.dart';
export 'src/components/fab/sb_fab.dart';
export 'src/components/search/sb_search_field.dart';
export 'src/components/empty_state/sb_empty_state.dart';
export 'src/components/sheet/sb_side_sheet.dart';
export 'src/components/banner/sb_banner.dart';
export 'src/components/snackbar/sb_snackbar.dart';
export 'src/components/carousel/sb_carousel.dart';
export 'src/components/list/sb_list.dart';
export 'src/components/breadcrumb/sb_breadcrumb.dart';
export 'src/components/pagination/sb_pagination.dart';
export 'src/components/skeleton/sb_shimmer.dart';
export 'src/components/tree/sb_tree_view.dart';
export 'src/components/tree/sb_checkable_tree_view.dart';
export 'src/components/menubar/sb_menubar.dart';
export 'src/components/input/sb_multi_select.dart';

// Icons (names only; generated by tool/generate_icon_names.dart).
export 'src/icons/supabase_icons.dart';
